name: Flutter Build for arm64 and armeabi-v7a

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the build
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.4'  # Replace with the Flutter version you need

      # Step 3: Verify Flutter installation
      - name: Print Flutter version
        run: flutter --version

      # Step 4: Get dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # Step 5: Build APK for arm64 and armeabi-v7a
      - name: Build APK for arm64 and armeabi-v7a
        run: |
          flutter build apk --release --target-platform android-arm,android-arm64

      # Step 6: Upload Release APK
      - name: Upload Release APK
        uses:
